/**
 * Created by yangkk on 17/2/28.
 * action类型
 */

// 侧边栏 actions
export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';
export const CHANGE_MATERIAL = 'CHANGE_MATERIAL';
export const CHANGE_PLATFORM = 'CHANGE_PLATFORM';


// user actions ////////////////////////////////////////
export const USER_LOGGING = 'USER_LOGGING';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

// 搜索 actions ////////////////////////////////////////

// 搜索全部
export const SEARCH_ALL_FETCH_LIST = 'SEARCH_ALL_FETCH_LIST';
export const SEARCH_ALL_RECEIVE_LIST = 'SEARCH_ALL_RECEIVE_LIST';
export const SEARCH_ALL_CLEAR_LIST = 'SEARCH_ALL_CLEAR_LIST';

// 搜索症状和问题
export const SEARCH_SYMPTOM_PROBLEM_FETCH_LIST = 'SEARCH_SYMPTOM_PROBLEM_FETCH_LIST';
export const SEARCH_SYMPTOM_PROBLEM_RECEIVE_LIST = 'SEARCH_SYMPTOM_PROBLEM_RECEIVE_LIST';
export const SEARCH_SYMPTOM_PROBLEM_CLEAR_LIST = 'SEARCH_SYMPTOM_PROBLEM_CLEAR_LIST';

// 搜索资讯
export const SEARCH_INFORMATION_FETCH_LIST = 'SEARCH_INFORMATION_FETCH_LIST';
export const SEARCH_INFORMATION_RECEIVE_LIST = 'SEARCH_INFORMATION_RECEIVE_LIST';
export const SEARCH_INFORMATION_CLEAR_LIST = 'SEARCH_INFORMATION_CLEAR_LIST';

// 搜索症状和问题
export const MY_COLLECTION_FETCH_LIST_FIRSTLOAD = 'MY_COLLECTION_FETCH_LIST_FIRSTLOAD';
export const MY_COLLECTION_FETCH_LIST_REFRESH = 'MY_COLLECTION_FETCH_LIST_REFRESH';
export const MY_COLLECTION_FETCH_LIST_PAGINATION = 'MY_COLLECTION_FETCH_LIST_PAGINATION';
export const MY_COLLECTION_RECEIVE_LIST = 'MY_COLLECTION_RECEIVE_LIST';


// dynamic actions ////////////////////////////////////////
export const NEW_DYNAMIC_ADD_PICTURE_ARR = 'NEW_DYNAMIC_ADD_PICTURE_ARR';
export const DYNAMIC_LIST_LOAD = 'DYNAMIC_LIST_FIRSTLOAD';
export const DYNAMIC_LIST_SHOW = 'DYNAMIC_LIST_SHOW';
export const DYNAMIC_LIST_ZAN_COMMENT = 'DYNAMIC_LIST_ZAN_COMMENT';
