'use strict';

// for user
export const LOGGED_IN = 'LOGGED_IN';
export const LOGGED_OUT = 'LOGGED_OUT';
export const LOGGED_ERROR = 'LOGGED_ERROR';
export const LOGGED_DOING = 'LOGGED_DOING';

export const FETCH_MESSAGE_LIST_RESULT = 'FETCH_MESSAGE_LIST_RESULT';
export const RECEIVE_MESSAGE_LIST_RESULT = 'RECEIVE_MESSAGE_LIST_RESULT';
