export const  questions= [
  {
    type:'laonianren',
    alltypes:[
      {
        type:'衰老问题',
        question:[{
            title:'反应迟钝',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'痴呆',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'耳聋',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'视觉障碍',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'口腔干燥',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'肥胖',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'骨质疏松',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'皮肤瘙痒',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'大便失禁',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'尿失禁',
            icon:require('../assets/1yuyue.png'),
          }]
      },
      {
        type:'日常问题',
        question:[{
            title:'头痛',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'口腔溃疡',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'咳嗽',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'感冒',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'咽炎',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'鼻炎',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'消化不良',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'胃炎',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'胃溃疡',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'腹泻',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'肠炎',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'便秘',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'失眠',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'呕吐',
            icon:require('../assets/1yuyue.png'),
          }]
      },
      {
        type:'慢性疾病',
        question:[{
            title:'高血压',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'高血脂',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'糖尿病',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'冠心病',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'中风',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'痛风',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'麻痹震颤',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'骨关节病',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'心肌梗塞',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'慢性支气管炎',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'肺炎',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'白内障',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'颈椎病',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'胆囊病',
            icon:require('../assets/1yuyue.png'),
          }]
      },
      {
        type:'意外伤害',
        question:[{
            title:'跌倒',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'噎食',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'中毒',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'晕厥',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'外伤',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'烫伤',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'癫痫',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'猝死',
            icon:require('../assets/1yuyue.png'),
          }]
      },
    ],
  },
  {
    type:'gaojingzhi',
    alltypes:[
      {
        type:'职业病',
        question:[{
            title:'失眠',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'肥胖',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'慢性疲劳',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'颈椎病',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'肩周炎',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'鼠标手',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'腱鞘炎',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'腰间盘突出',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'腰肌劳损',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'干眼症',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'冠心病',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'胃炎',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'消化不良',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'皮肤过敏',
            icon:require('../assets/1yuyue.png'),
          }]
      },
      {
        type:'日常问题',
        question:[{
            title:'头痛',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'口腔溃疡',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'咳嗽',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'感冒',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'咽炎',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'鼻炎',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'消化不良',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'胃炎',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'口臭',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'结膜炎',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'便秘',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'腹泻',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'呕吐',
            icon:require('../assets/1yuyue.png'),
          }]
      },
    ],
  },
  {
    type:'nvxingzhengchang',
    alltypes:[
      {
        type:'职业病',
        question:[{
            title:'失眠',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'肥胖',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'慢性疲劳',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'颈椎病',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'肩周炎',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'鼠标手',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'腱鞘炎',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'腰间盘突出',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'腰肌劳损',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'干眼症',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'冠心病',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'胃炎',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'消化不良',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'皮肤过敏',
            icon:require('../assets/1yuyue.png'),
          }]
      },
      {
        type:'经期问题',
        question:[{
            title:'痛经',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'经前期紧张',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'闭经',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'月经周期异常',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'月经量异常',
            icon:require('../assets/1yuyue.png'),
          }]
      },
      {
        type:'更年期问题',
        question:[{
            title:'潮红',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'潮热汗出',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'发冷',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'腰酸背痛',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'胸闷心慌',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'过瘦',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'体脂增加',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'味觉丧失',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'老花眼',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'注意力下降',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'乳房萎缩',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'肌肉无力',
            icon:require('../assets/1yuyue.png'),
          }]
      },
      {
        type:'日常问题',
        question:[{
            title:'头痛',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'低血糖',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'低血压',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'贫血',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'水肿',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'肥胖',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'牙龈出血',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'眩晕',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'失眠',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'畏寒',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'口臭',
            icon:require('../assets/1yuyue.png'),
          }]
      },
    ],
  },
  {
    type:'daichang',
    alltypes:[
      {
        type:'孕早期问题（0-3个月）',
        question:[{
            title:'孕吐',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'疲劳（困倦）',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'疼痛',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'尿频',
            icon:require('../assets/1yuyue.png'),
          }]
      },
      {
        type:'孕中期问题（4-7个月）',
        question:[{
            title:'腹痛',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'腹胀',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'眩晕',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'贫血',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'糖尿病',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'妊娠中毒',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'乳头凹陷',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'皮肤瘙痒',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'失眠',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'食欲不振',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'便秘',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'痔疮',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'小腿水肿',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'腿部抽筋',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'静脉曲张',
            icon:require('../assets/1yuyue.png'),
          },
        ]
      },
      {
        type:'孕晚期问题（8个月-临盆）',
        question:[{
            title:'体重增加过快',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'呼吸短促',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'脸部水肿',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'肋下疼痛',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'腹部皮肤瘙痒',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'腹部发紧',
            icon:require('../assets/1yuyue.png'),
          },
          {
            title:'站立骨盆疼痛',
            icon:require('../assets/1yuyue.png'),
          }]
        }
    ],
  },
]
