-- MySQL Script generated by MySQL Workbench
-- Mon Apr  3 21:28:41 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fudao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fudao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fudao` DEFAULT CHARACTER SET utf8 ;
USE `fudao` ;

-- -----------------------------------------------------
-- Table `fudao`.`renqun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`renqun` (
  `id` INT NOT NULL COMMENT '人群ID',
  `name` VARCHAR(45) NULL COMMENT '名称',
  `title` VARCHAR(45) NULL COMMENT '标题',
  `remark` VARCHAR(45) NULL COMMENT '备注',
  `order_num` INT NULL COMMENT '排序号',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '人群';


-- -----------------------------------------------------
-- Table `fudao`.`disease_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`disease_type` (
  `id` VARCHAR(45) NOT NULL COMMENT 'ID',
  `name` VARCHAR(45) NULL COMMENT '分类名称',
  `order_num` VARCHAR(45) NULL COMMENT '排序号',
  `renqun_id` INT NOT NULL COMMENT '人群ID',
  PRIMARY KEY (`id`),
  INDEX `fk_disease_type_renqun1_idx` (`renqun_id` ASC),
  CONSTRAINT `fk_disease_type_renqun1`
    FOREIGN KEY (`renqun_id`)
    REFERENCES `fudao`.`renqun` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '人群疾病类型';


-- -----------------------------------------------------
-- Table `fudao`.`disease`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`disease` (
  `id` VARCHAR(45) NOT NULL COMMENT 'ID',
  `name` VARCHAR(45) NULL COMMENT '疾病名称',
  `title` VARCHAR(45) NULL COMMENT '疾病显示名称',
  `img` VARCHAR(255) NULL COMMENT '图片',
  `order_num` INT NULL COMMENT '排序号',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5
COLLATE = big5_bin
COMMENT = '疾病';


-- -----------------------------------------------------
-- Table `fudao`.`disease_disease_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`disease_disease_type` (
  `disease_type_id` VARCHAR(45) NOT NULL COMMENT '疾病分类ID',
  `disease_id` VARCHAR(45) NOT NULL COMMENT '疾病ID',
  INDEX `fk_disease_disease_type_disease1_idx` (`disease_id` ASC),
  INDEX `fk_disease_disease_type_disease_type1_idx` (`disease_type_id` ASC),
  PRIMARY KEY (`disease_type_id`, `disease_id`),
  CONSTRAINT `fk_disease_disease_type_disease1`
    FOREIGN KEY (`disease_id`)
    REFERENCES `fudao`.`disease` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disease_disease_type_disease_type1`
    FOREIGN KEY (`disease_type_id`)
    REFERENCES `fudao`.`disease_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '疾病分类 <=> 疾病';


-- -----------------------------------------------------
-- Table `fudao`.`ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`ingredients` (
  `id` VARCHAR(45) NOT NULL COMMENT 'ID',
  `name` VARCHAR(255) NULL COMMENT '食材名称',
  `other_name` VARCHAR(255) NULL COMMENT '其他的名字',
  `energy` VARCHAR(255) NULL COMMENT '能量',
  `protein` VARCHAR(255) NULL COMMENT '蛋白质',
  `fat` VARCHAR(255) NULL COMMENT '脂肪',
  `carbohydrate` VARCHAR(255) NULL COMMENT ' 碳水化合物 ',
  `dietary_fiber` VARCHAR(255) NULL COMMENT '膳食纤维',
  `cholesterol` VARCHAR(255) NULL COMMENT '胆固醇',
  `abstract` TEXT NULL COMMENT '摘要',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '食材';


-- -----------------------------------------------------
-- Table `fudao`.`cookbook`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`cookbook` (
  `id` VARCHAR(45) NOT NULL COMMENT 'ID',
  `name` VARCHAR(255) NULL COMMENT '菜名',
  `time_period` VARCHAR(255) NULL COMMENT '使用时段',
  `type` VARCHAR(255) NULL COMMENT '类型\n1:菜品\n2:主食',
  `main_ingredient` VARCHAR(255) NULL COMMENT '主料',
  `auxiliary_ingredient` VARCHAR(255) NULL COMMENT '辅料',
  `ingredients` VARCHAR(255) NULL COMMENT '包含食材',
  `steps` TEXT NULL COMMENT '做法步骤',
  `img` VARCHAR(255) NULL COMMENT '菜品图片',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '菜谱';


-- -----------------------------------------------------
-- Table `fudao`.`time_stage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`time_stage` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL COMMENT '时段名称',
  `title` VARCHAR(45) NULL COMMENT '备注名称',
  `level` VARCHAR(45) NULL COMMENT '时段级别',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '时间阶段';


-- -----------------------------------------------------
-- Table `fudao`.`time_period`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`time_period` (
  `id` INT NOT NULL COMMENT '分段ID',
  `time_stage_id` INT NOT NULL COMMENT '时间阶段ID',
  `name` VARCHAR(45) NULL COMMENT '分段名称',
  `title` VARCHAR(45) NULL COMMENT '分段备注名称',
  `is_start_remind` INT NULL COMMENT '是否开始时间提醒，\n0:不提醒，\n1:提醒',
  `is_end_remind` INT NULL COMMENT '是否结束时间提醒，\n0:不提醒，\n1:提醒',
  PRIMARY KEY (`id`),
  INDEX `fk_time_segment_time_stage1_idx` (`time_stage_id` ASC),
  CONSTRAINT `fk_time_segment_time_stage1`
    FOREIGN KEY (`time_stage_id`)
    REFERENCES `fudao`.`time_stage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '时间分段';


-- -----------------------------------------------------
-- Table `fudao`.`season`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`season` (
  `id` INT NOT NULL COMMENT '季节ID',
  `name` VARCHAR(45) NULL COMMENT '季节名称',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '季节';


-- -----------------------------------------------------
-- Table `fudao`.`solar_term`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`solar_term` (
  `id` INT NOT NULL COMMENT '节气ID',
  `name` VARCHAR(45) NULL COMMENT '节气名称',
  `season_id` INT NOT NULL COMMENT '季节ID',
  PRIMARY KEY (`id`),
  INDEX `fk_solar_term_season1_idx` (`season_id` ASC),
  CONSTRAINT `fk_solar_term_season1`
    FOREIGN KEY (`season_id`)
    REFERENCES `fudao`.`season` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '节气';


-- -----------------------------------------------------
-- Table `fudao`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`region` (
  `id` VARCHAR(6) NOT NULL COMMENT '行政区划代码',
  `name` VARCHAR(45) NULL COMMENT '行政区划名称',
  `full_name` VARCHAR(255) NULL COMMENT '全名',
  `level` INT NULL COMMENT '级别，1：一级，2：二级，3：三级',
  `parent_id` VARCHAR(6) NULL COMMENT '上级代码',
  PRIMARY KEY (`id`),
  INDEX `fk_region_region1_idx` (`parent_id` ASC),
  CONSTRAINT `fk_region_region1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `fudao`.`region` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '行政区划';


-- -----------------------------------------------------
-- Table `fudao`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`user` (
  `id` VARCHAR(45) NOT NULL COMMENT 'ID',
  `username` VARCHAR(45) NULL COMMENT '用户名',
  `password` VARCHAR(45) NULL COMMENT '密码',
  `phone` VARCHAR(45) NULL COMMENT '手机号',
  `email` VARCHAR(45) NULL COMMENT '电子邮箱',
  `nickname` VARCHAR(45) NULL COMMENT '昵称',
  `name` VARCHAR(45) NULL COMMENT '姓名',
  `photo` VARCHAR(255) NULL COMMENT '头像',
  `sex` INT NULL COMMENT '性别，男：1,女：2',
  `birthday` DATE NULL COMMENT '出生日期',
  `height` DECIMAL(3,0) NULL COMMENT '身高(cm)',
  `weight` DECIMAL(3,1) NULL COMMENT '体重(kg)',
  `personal_history` VARCHAR(1000) NULL COMMENT '个人史',
  `family_history` VARCHAR(255) NULL COMMENT '家族史',
  `obstetrical_history` VARCHAR(255) NULL COMMENT '婚育史',
  `medication_history` VARCHAR(255) NULL COMMENT '用药史',
  `diet` VARCHAR(255) NULL COMMENT '饮食',
  `motion` VARCHAR(255) NULL COMMENT '运动',
  `sleep` VARCHAR(255) NULL COMMENT '睡眠',
  `smoke` VARCHAR(255) NULL COMMENT '吸烟',
  `drink` VARCHAR(255) NULL COMMENT '饮酒',
  `mental_state` VARCHAR(255) NULL COMMENT '精神状态',
  `woman_type` INT NULL COMMENT '女人类型，1：未孕，2：备孕，3：待产，4：产后，5：已育',
  `region_id` VARCHAR(6) NOT NULL COMMENT '地区',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_user_region1_idx` (`region_id` ASC),
  CONSTRAINT `fk_user_region1`
    FOREIGN KEY (`region_id`)
    REFERENCES `fudao`.`region` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '用户';


-- -----------------------------------------------------
-- Table `fudao`.`day_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`day_type` (
  `id` INT NOT NULL COMMENT 'ID',
  `name` VARCHAR(45) NULL COMMENT '名称',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '周天类型，1：工作日，2：周末';


-- -----------------------------------------------------
-- Table `fudao`.`user_time_stage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`user_time_stage` (
  `id` VARCHAR(45) NOT NULL COMMENT 'ID',
  `user_id` VARCHAR(45) NOT NULL COMMENT '用户ID',
  `day_type_id` INT NOT NULL COMMENT '日类型ID',
  `time_stage_id` INT NOT NULL COMMENT '时间阶段ID',
  `start_time` VARCHAR(45) NULL COMMENT '开始时间',
  `emd_time` VARCHAR(45) NULL COMMENT '结束时间',
  `start_time_range` VARCHAR(45) NULL COMMENT '开始时间范围',
  `end_time_range` VARCHAR(45) NULL COMMENT '结束时间范围',
  `time_len_range_min` INT NULL COMMENT '时间长度范围限制最小值(min)',
  `time_len_range_max` INT NULL COMMENT '时间长度范围限制最大值(min)',
  PRIMARY KEY (`id`),
  INDEX `fk_user_time_period_user1_idx` (`user_id` ASC),
  INDEX `fk_user_time_period_day_type1_idx` (`day_type_id` ASC),
  INDEX `fk_user_time_stage_time_stage1_idx` (`time_stage_id` ASC),
  CONSTRAINT `fk_user_time_period_user10`
    FOREIGN KEY (`user_id`)
    REFERENCES `fudao`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_time_period_day_type10`
    FOREIGN KEY (`day_type_id`)
    REFERENCES `fudao`.`day_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_time_stage_time_stage1`
    FOREIGN KEY (`time_stage_id`)
    REFERENCES `fudao`.`time_stage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '用户时间阶段';


-- -----------------------------------------------------
-- Table `fudao`.`user_time_period`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`user_time_period` (
  `id` VARCHAR(45) NOT NULL COMMENT 'ID',
  `user_time_stage_id` VARCHAR(45) NOT NULL,
  `time_period_id` INT NOT NULL,
  `start_time` VARCHAR(45) NULL COMMENT '时间段数据(json)',
  `emd_time` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_time_period_time_period1_idx` (`time_period_id` ASC),
  INDEX `fk_user_time_period_user_time_stage1_idx` (`user_time_stage_id` ASC),
  CONSTRAINT `fk_user_time_period_time_period1`
    FOREIGN KEY (`time_period_id`)
    REFERENCES `fudao`.`time_period` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_time_period_user_time_stage1`
    FOREIGN KEY (`user_time_stage_id`)
    REFERENCES `fudao`.`user_time_stage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '我的时间段';


-- -----------------------------------------------------
-- Table `fudao`.`energy_indicator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`energy_indicator` (
  `id` VARCHAR(45) NOT NULL COMMENT 'ID',
  `name` VARCHAR(45) NULL COMMENT '指标名称',
  `order_num` INT NULL COMMENT '排序号',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '能量场指标';


-- -----------------------------------------------------
-- Table `fudao`.`energy_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`energy_data` (
  `id` INT NOT NULL COMMENT 'ID',
  `user_id` VARCHAR(45) NULL COMMENT '用户ID',
  `energy_indicator_id` VARCHAR(45) NOT NULL,
  `value` INT NULL COMMENT '指标ID',
  PRIMARY KEY (`id`),
  INDEX `fk_energy_data_energy_indicator1_idx` (`energy_indicator_id` ASC),
  CONSTRAINT `fk_energy_data_energy_indicator1`
    FOREIGN KEY (`energy_indicator_id`)
    REFERENCES `fudao`.`energy_indicator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '能量场数据';


-- -----------------------------------------------------
-- Table `fudao`.`zixiu_part`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`zixiu_part` (
  `id` VARCHAR(45) NOT NULL COMMENT 'ID',
  `name` VARCHAR(45) NULL COMMENT '部位名称',
  `order_num` INT NULL COMMENT '排序号',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '自修部位';


-- -----------------------------------------------------
-- Table `fudao`.`zixiu_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`zixiu_project` (
  `id` VARCHAR(45) NOT NULL COMMENT 'ID',
  `name` VARCHAR(45) NULL COMMENT '项目名称',
  `img` VARCHAR(45) NULL COMMENT '项目图标',
  `order_num` VARCHAR(45) NULL COMMENT '排序号',
  `zixiu_part_id` VARCHAR(45) NOT NULL COMMENT '自修部位ID',
  `renqun` VARCHAR(45) NULL COMMENT '适用的人群，多人群用英文逗号隔开',
  PRIMARY KEY (`id`),
  INDEX `fk_zixiu_project_zixiu_part1_idx` (`zixiu_part_id` ASC),
  CONSTRAINT `fk_zixiu_project_zixiu_part1`
    FOREIGN KEY (`zixiu_part_id`)
    REFERENCES `fudao`.`zixiu_part` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '自修项目';


-- -----------------------------------------------------
-- Table `fudao`.`user_zixiu_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`user_zixiu_project` (
  `user_id` VARCHAR(45) NOT NULL COMMENT '用户ID',
  `zixiu_project_id` VARCHAR(45) NOT NULL COMMENT '自修项目ID',
  `order_num` VARCHAR(45) NULL COMMENT '排序号',
  PRIMARY KEY (`zixiu_project_id`, `user_id`),
  INDEX `fk_user_zixiu_project_user1_idx` (`user_id` ASC),
  INDEX `fk_user_zixiu_project_zixiu_project1_idx` (`zixiu_project_id` ASC),
  CONSTRAINT `fk_user_zixiu_project_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fudao`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_zixiu_project_zixiu_project1`
    FOREIGN KEY (`zixiu_project_id`)
    REFERENCES `fudao`.`zixiu_project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '用户自修项目';


-- -----------------------------------------------------
-- Table `fudao`.`professional_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`professional_method` (
  `id` VARCHAR(45) NOT NULL COMMENT 'ID',
  `name` VARCHAR(45) NULL COMMENT '方法名称',
  `type` VARCHAR(45) NULL COMMENT '方法分类',
  `material` TEXT NULL COMMENT '原料',
  `making_method` TEXT NULL COMMENT '制作方法',
  `usage_method` TEXT NULL COMMENT '使用方法',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '专业疗法';


-- -----------------------------------------------------
-- Table `fudao`.`daily_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`daily_method` (
  `id` VARCHAR(45) NOT NULL COMMENT 'ID',
  `name` VARCHAR(255) NULL COMMENT '方法名称',
  `principle` TEXT NULL COMMENT '原理',
  `three_character_classic` TEXT NULL COMMENT '三字经',
  `details` TEXT NULL COMMENT '方法详情',
  `img` VARCHAR(255) NULL COMMENT '附件：图片/音频/视频',
  `type` INT NULL COMMENT '方法分类，1:起居；2:动；3:静；4:娱乐；\n',
  `part` VARCHAR(45) NULL COMMENT '动的部位',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '日常方法';


-- -----------------------------------------------------
-- Table `fudao`.`diet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`diet` (
  `id` VARCHAR(45) NOT NULL,
  `suitable` TEXT NULL COMMENT '宜食',
  `fasting` TEXT NULL COMMENT '禁食',
  `dishes_ingredients` TEXT NULL COMMENT '推荐菜品食材',
  `staple_ingredients` TEXT NULL COMMENT '推荐主食食材',
  `breakfast_ingredients` TEXT NULL COMMENT '推荐早餐食材',
  `tea_ingredients` TEXT NULL COMMENT '推荐茶歇食材',
  `disable_ingredients` TEXT NULL COMMENT '禁用食材',
  `disable_cooking_methods` TEXT NULL COMMENT '禁用烹饪方法',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '饮食';


-- -----------------------------------------------------
-- Table `fudao`.`article_column`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`article_column` (
  `id` VARCHAR(45) NOT NULL COMMENT '栏目ID',
  `name` VARCHAR(45) NULL COMMENT '栏目名称',
  `order_num` INT NULL COMMENT '排序号',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '资讯栏目';


-- -----------------------------------------------------
-- Table `fudao`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`article` (
  `id` VARCHAR(45) NOT NULL COMMENT 'ID',
  `title` VARCHAR(255) NULL COMMENT '标题',
  `content` TEXT NULL COMMENT '内容',
  `article_column_id` VARCHAR(45) NOT NULL COMMENT '所属栏目ID',
  `img` VARCHAR(255) NULL COMMENT '图片',
  `source` VARCHAR(45) NULL COMMENT '来源',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `renqun` VARCHAR(1000) NULL COMMENT '指定适用的人群，null代表是适用所有人群，多人群用逗号分隔',
  PRIMARY KEY (`id`),
  INDEX `fk_article_article_column1_idx` (`article_column_id` ASC),
  CONSTRAINT `fk_article_article_column1`
    FOREIGN KEY (`article_column_id`)
    REFERENCES `fudao`.`article_column` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '资讯';


-- -----------------------------------------------------
-- Table `fudao`.`zixun_diet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`zixun_diet` (
  `diet_id` VARCHAR(45) NOT NULL COMMENT '饮食ID',
  `zixiu_project_id` VARCHAR(45) NOT NULL COMMENT '自修项目ID',
  INDEX `fk_zixun_diet_zixiu_project1_idx` (`zixiu_project_id` ASC),
  INDEX `fk_zixun_diet_diet1_idx` (`diet_id` ASC),
  PRIMARY KEY (`diet_id`, `zixiu_project_id`),
  CONSTRAINT `fk_zixun_diet_zixiu_project1`
    FOREIGN KEY (`zixiu_project_id`)
    REFERENCES `fudao`.`zixiu_project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zixun_diet_diet1`
    FOREIGN KEY (`diet_id`)
    REFERENCES `fudao`.`diet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '自修饮食';


-- -----------------------------------------------------
-- Table `fudao`.`zixiu_daily_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`zixiu_daily_method` (
  `daily_method_id` VARCHAR(45) NOT NULL COMMENT '日常方法ID',
  `zixiu_project_id` VARCHAR(45) NOT NULL COMMENT '自修项目ID',
  `renqun_id` INT NOT NULL COMMENT '适用人群',
  `day_type_id` INT NOT NULL COMMENT '适用的天',
  `time_period_id` INT NOT NULL COMMENT '适用时段',
  INDEX `fk_zixiu_daily_method_zixiu_project1_idx` (`zixiu_project_id` ASC),
  INDEX `fk_zixiu_daily_method_daily_method1_idx` (`daily_method_id` ASC),
  PRIMARY KEY (`daily_method_id`, `zixiu_project_id`, `renqun_id`, `time_period_id`, `day_type_id`),
  INDEX `fk_zixiu_daily_method_renqun1_idx` (`renqun_id` ASC),
  INDEX `fk_zixiu_daily_method_time_period1_idx` (`time_period_id` ASC),
  INDEX `fk_zixiu_daily_method_day_type1_idx` (`day_type_id` ASC),
  CONSTRAINT `fk_zixiu_daily_method_zixiu_project1`
    FOREIGN KEY (`zixiu_project_id`)
    REFERENCES `fudao`.`zixiu_project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zixiu_daily_method_daily_method1`
    FOREIGN KEY (`daily_method_id`)
    REFERENCES `fudao`.`daily_method` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zixiu_daily_method_renqun1`
    FOREIGN KEY (`renqun_id`)
    REFERENCES `fudao`.`renqun` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zixiu_daily_method_time_period1`
    FOREIGN KEY (`time_period_id`)
    REFERENCES `fudao`.`time_period` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zixiu_daily_method_day_type1`
    FOREIGN KEY (`day_type_id`)
    REFERENCES `fudao`.`day_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '自修日常方法';


-- -----------------------------------------------------
-- Table `fudao`.`zixiu_professional_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`zixiu_professional_method` (
  `professional_method_id` VARCHAR(45) NOT NULL COMMENT '专业方法ID',
  `zixiu_project_id` VARCHAR(45) NOT NULL COMMENT '自修项目ID',
  INDEX `fk_zixiu_professional_method_zixiu_project1_idx` (`zixiu_project_id` ASC),
  INDEX `fk_zixiu_professional_method_professional_method1_idx` (`professional_method_id` ASC),
  PRIMARY KEY (`professional_method_id`, `zixiu_project_id`),
  CONSTRAINT `fk_zixiu_professional_method_zixiu_project1`
    FOREIGN KEY (`zixiu_project_id`)
    REFERENCES `fudao`.`zixiu_project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zixiu_professional_method_professional_method1`
    FOREIGN KEY (`professional_method_id`)
    REFERENCES `fudao`.`professional_method` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '自修专业方法';


-- -----------------------------------------------------
-- Table `fudao`.`disease_diet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`disease_diet` (
  `diet_id` VARCHAR(45) NOT NULL,
  `disease_id` VARCHAR(45) NOT NULL,
  `renqun_id` INT NOT NULL,
  INDEX `fk_disease_diet_disease1_idx` (`disease_id` ASC),
  INDEX `fk_disease_diet_diet1_idx` (`diet_id` ASC),
  INDEX `fk_disease_diet_renqun1_idx` (`renqun_id` ASC),
  PRIMARY KEY (`diet_id`, `disease_id`, `renqun_id`),
  CONSTRAINT `fk_disease_diet_disease1`
    FOREIGN KEY (`disease_id`)
    REFERENCES `fudao`.`disease` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disease_diet_diet1`
    FOREIGN KEY (`diet_id`)
    REFERENCES `fudao`.`diet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disease_diet_renqun1`
    FOREIGN KEY (`renqun_id`)
    REFERENCES `fudao`.`renqun` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '疾病饮食';


-- -----------------------------------------------------
-- Table `fudao`.`disease_daily_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`disease_daily_method` (
  `daily_method_id` VARCHAR(45) NOT NULL COMMENT '日常方法ID',
  `disease_id` VARCHAR(45) NOT NULL COMMENT '适合的疾病',
  `renqun_id` INT NOT NULL COMMENT '适用的人群',
  `day_type_id` INT NOT NULL COMMENT '适用的天',
  `time_period_id` INT NOT NULL COMMENT '适用的时段',
  INDEX `fk_disease_daily_method_disease1_idx` (`disease_id` ASC),
  INDEX `fk_disease_daily_method_daily_method1_idx` (`daily_method_id` ASC),
  INDEX `fk_disease_daily_method_renqun1_idx` (`renqun_id` ASC),
  INDEX `fk_disease_daily_method_time_period1_idx` (`time_period_id` ASC),
  PRIMARY KEY (`daily_method_id`, `disease_id`, `renqun_id`, `time_period_id`, `day_type_id`),
  INDEX `fk_disease_daily_method_day_type1_idx` (`day_type_id` ASC),
  CONSTRAINT `fk_disease_daily_method_disease1`
    FOREIGN KEY (`disease_id`)
    REFERENCES `fudao`.`disease` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disease_daily_method_daily_method1`
    FOREIGN KEY (`daily_method_id`)
    REFERENCES `fudao`.`daily_method` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disease_daily_method_renqun1`
    FOREIGN KEY (`renqun_id`)
    REFERENCES `fudao`.`renqun` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disease_daily_method_time_period1`
    FOREIGN KEY (`time_period_id`)
    REFERENCES `fudao`.`time_period` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disease_daily_method_day_type1`
    FOREIGN KEY (`day_type_id`)
    REFERENCES `fudao`.`day_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '疾病日常方法';


-- -----------------------------------------------------
-- Table `fudao`.`disease_professional_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`disease_professional_method` (
  `professional_method_id` VARCHAR(45) NOT NULL COMMENT '专业方法ID',
  `disease_id` VARCHAR(45) NOT NULL COMMENT '适用的疾病',
  `renqun_id` INT NOT NULL COMMENT '适用的人群',
  INDEX `fk_disease_professional_method_disease1_idx` (`disease_id` ASC),
  INDEX `fk_disease_professional_method_professional_method1_idx` (`professional_method_id` ASC),
  INDEX `fk_disease_professional_method_renqun1_idx` (`renqun_id` ASC),
  PRIMARY KEY (`professional_method_id`, `disease_id`, `renqun_id`),
  CONSTRAINT `fk_disease_professional_method_disease1`
    FOREIGN KEY (`disease_id`)
    REFERENCES `fudao`.`disease` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disease_professional_method_professional_method1`
    FOREIGN KEY (`professional_method_id`)
    REFERENCES `fudao`.`professional_method` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disease_professional_method_renqun1`
    FOREIGN KEY (`renqun_id`)
    REFERENCES `fudao`.`renqun` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '疾病专业方法';


-- -----------------------------------------------------
-- Table `fudao`.`health_diet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`health_diet` (
  `diet_id` VARCHAR(45) NOT NULL COMMENT '饮食ID',
  `solar_term_id` INT NOT NULL COMMENT '适用节气',
  INDEX `fk_solar_term_diet_solar_term1_idx` (`solar_term_id` ASC),
  INDEX `fk_solar_term_diet_diet1_idx` (`diet_id` ASC),
  PRIMARY KEY (`diet_id`, `solar_term_id`),
  CONSTRAINT `fk_solar_term_diet_solar_term1`
    FOREIGN KEY (`solar_term_id`)
    REFERENCES `fudao`.`solar_term` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solar_term_diet_diet1`
    FOREIGN KEY (`diet_id`)
    REFERENCES `fudao`.`diet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '健康养生饮食';


-- -----------------------------------------------------
-- Table `fudao`.`health_daily_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`health_daily_method` (
  `daily_method_id` VARCHAR(45) NOT NULL COMMENT '日常方法ID',
  `solar_term_id` INT NOT NULL COMMENT '适用节气',
  `renqun_id` INT NOT NULL COMMENT '适用人群',
  `day_type_id` INT NOT NULL COMMENT '适用的天',
  `time_period_id` INT NOT NULL COMMENT '适用时段',
  INDEX `fk_solar_term_daily_method_solar_term1_idx` (`solar_term_id` ASC),
  INDEX `fk_solar_term_daily_method_daily_method1_idx` (`daily_method_id` ASC),
  INDEX `fk_solar_term_daily_method_renqun1_idx` (`renqun_id` ASC),
  INDEX `fk_solar_term_daily_method_time_period1_idx` (`time_period_id` ASC),
  PRIMARY KEY (`daily_method_id`, `solar_term_id`, `renqun_id`, `time_period_id`, `day_type_id`),
  INDEX `fk_health_daily_method_day_type1_idx` (`day_type_id` ASC),
  CONSTRAINT `fk_solar_term_daily_method_solar_term1`
    FOREIGN KEY (`solar_term_id`)
    REFERENCES `fudao`.`solar_term` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solar_term_daily_method_daily_method1`
    FOREIGN KEY (`daily_method_id`)
    REFERENCES `fudao`.`daily_method` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solar_term_daily_method_renqun1`
    FOREIGN KEY (`renqun_id`)
    REFERENCES `fudao`.`renqun` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solar_term_daily_method_time_period1`
    FOREIGN KEY (`time_period_id`)
    REFERENCES `fudao`.`time_period` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_health_daily_method_day_type1`
    FOREIGN KEY (`day_type_id`)
    REFERENCES `fudao`.`day_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '健康养生日常方法';


-- -----------------------------------------------------
-- Table `fudao`.`location_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`location_type` (
  `id` INT NOT NULL COMMENT 'ID',
  `name` VARCHAR(45) NULL COMMENT '地区名称',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '地区类型，1：除新疆、西藏外的所有地区，2：新疆、西藏地区。';


-- -----------------------------------------------------
-- Table `fudao`.`general_time_stage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`general_time_stage` (
  `id` VARCHAR(45) NOT NULL,
  `renqun_id` INT NOT NULL COMMENT '人群ID',
  `season_id` INT NOT NULL COMMENT '季节ID',
  `location_type_id` INT NOT NULL COMMENT '地区类型ID',
  `day_type_id` INT NOT NULL COMMENT '日类型ID',
  `time_stage_id` INT NOT NULL COMMENT '时间阶段ID',
  `start_time` VARCHAR(45) NULL COMMENT '开始时间',
  `end_time` VARCHAR(45) NULL COMMENT '结束时间',
  `start_time_range` VARCHAR(45) NULL COMMENT '开始时间调整范围',
  `end_time_range` VARCHAR(45) NULL COMMENT '结束时间调整范围',
  `time_len_range_min` INT NULL COMMENT '时间长度范围限制最小值(min)',
  `time_len_reane_max` INT NULL COMMENT '时间长度范围限制最大值(min)',
  PRIMARY KEY (`id`),
  INDEX `fk_time_stage_renqun1_idx` (`renqun_id` ASC),
  INDEX `fk_time_stage_copy1_day_type1_idx` (`day_type_id` ASC),
  INDEX `fk_time_stage_copy1_season1_idx` (`season_id` ASC),
  INDEX `fk_time_stage_copy1_location_type1_idx` (`location_type_id` ASC),
  INDEX `fk_general_time_stage_time_stage1_idx` (`time_stage_id` ASC),
  CONSTRAINT `fk_time_stage_renqun10`
    FOREIGN KEY (`renqun_id`)
    REFERENCES `fudao`.`renqun` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_time_stage_copy1_day_type1`
    FOREIGN KEY (`day_type_id`)
    REFERENCES `fudao`.`day_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_time_stage_copy1_season1`
    FOREIGN KEY (`season_id`)
    REFERENCES `fudao`.`season` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_time_stage_copy1_location_type1`
    FOREIGN KEY (`location_type_id`)
    REFERENCES `fudao`.`location_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_general_time_stage_time_stage1`
    FOREIGN KEY (`time_stage_id`)
    REFERENCES `fudao`.`time_stage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '通用时间阶段';


-- -----------------------------------------------------
-- Table `fudao`.`general_time_period`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`general_time_period` (
  `id` VARCHAR(45) NOT NULL COMMENT '分段ID',
  `general_time_stage_id` VARCHAR(45) NOT NULL COMMENT '通用时间阶段ID',
  `time_period_id` INT NOT NULL COMMENT '时间段ID',
  `start_time` VARCHAR(45) NULL COMMENT '开始时间 ',
  `end_time` VARCHAR(45) NULL COMMENT '结束时间',
  PRIMARY KEY (`id`),
  INDEX `fk_general_time_period_general_time_stage1_idx` (`general_time_stage_id` ASC),
  INDEX `fk_general_time_period_time_period1_idx` (`time_period_id` ASC),
  CONSTRAINT `fk_general_time_period_general_time_stage1`
    FOREIGN KEY (`general_time_stage_id`)
    REFERENCES `fudao`.`general_time_stage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_general_time_period_time_period1`
    FOREIGN KEY (`time_period_id`)
    REFERENCES `fudao`.`time_period` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '通用时间分段';


-- -----------------------------------------------------
-- Table `fudao`.`article_renqun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`article_renqun` (
  `article_id` VARCHAR(45) NOT NULL COMMENT '资讯ID',
  `renqun_id` INT NOT NULL COMMENT '适用人群ID',
  INDEX `fk_article_renqun_article1_idx` (`article_id` ASC),
  INDEX `fk_article_renqun_renqun1_idx` (`renqun_id` ASC),
  CONSTRAINT `fk_article_renqun_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `fudao`.`article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_renqun_renqun1`
    FOREIGN KEY (`renqun_id`)
    REFERENCES `fudao`.`renqun` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '资讯适用人群';


-- -----------------------------------------------------
-- Table `fudao`.`user_disease`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`user_disease` (
  `user_id` VARCHAR(45) NOT NULL COMMENT '用户ID',
  `disease_id` VARCHAR(45) NOT NULL COMMENT '疾病ID',
  `order_num` INT NULL COMMENT '排序号',
  INDEX `fk_user_disease_user1_idx` (`user_id` ASC),
  INDEX `fk_user_disease_disease1_idx` (`disease_id` ASC),
  PRIMARY KEY (`user_id`, `disease_id`),
  CONSTRAINT `fk_user_disease_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fudao`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_disease_disease1`
    FOREIGN KEY (`disease_id`)
    REFERENCES `fudao`.`disease` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '用户疾病';


-- -----------------------------------------------------
-- Table `fudao`.`dynamic_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`dynamic_type` (
  `id` INT NOT NULL COMMENT 'ID',
  `name` VARCHAR(45) NULL COMMENT '类型名称',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '动态类型';


-- -----------------------------------------------------
-- Table `fudao`.`dynamic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`dynamic` (
  `id` VARCHAR(45) NOT NULL COMMENT 'ID',
  `user_id` VARCHAR(45) NOT NULL COMMENT '发表人',
  `content` TEXT NULL COMMENT '内容',
  `create_time` DATETIME NULL COMMENT '发表时间',
  `dynamic_type_id` INT NOT NULL COMMENT '动态类型',
  `path` TEXT NULL COMMENT '路径',
  INDEX `fk_dynamic_user1_idx` (`user_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_dynamic_dynamic_type1_idx` (`dynamic_type_id` ASC),
  CONSTRAINT `fk_dynamic_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fudao`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dynamic_dynamic_type1`
    FOREIGN KEY (`dynamic_type_id`)
    REFERENCES `fudao`.`dynamic_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '动态';


-- -----------------------------------------------------
-- Table `fudao`.`dynamic_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`dynamic_comment` (
  `id` VARCHAR(45) NOT NULL COMMENT 'ID',
  `dynamic_id` VARCHAR(45) NOT NULL COMMENT '动态ID',
  `user_id` VARCHAR(45) NOT NULL COMMENT '评论人ID',
  `content` VARCHAR(500) NULL COMMENT '评论内容',
  `create_time` DATETIME NULL COMMENT '评论时间',
  PRIMARY KEY (`id`),
  INDEX `fk_dynamic_comment_dynamic1_idx` (`dynamic_id` ASC),
  INDEX `fk_dynamic_comment_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_dynamic_comment_dynamic1`
    FOREIGN KEY (`dynamic_id`)
    REFERENCES `fudao`.`dynamic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dynamic_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fudao`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '动态评论';


-- -----------------------------------------------------
-- Table `fudao`.`dynamic_praise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`dynamic_praise` (
  `dynamic_id` VARCHAR(45) NOT NULL COMMENT '动态ID',
  `user_id` VARCHAR(45) NOT NULL COMMENT '点赞用户ID',
  `create_time` DATETIME NULL COMMENT '点赞时间',
  PRIMARY KEY (`dynamic_id`, `user_id`),
  INDEX `fk_dynamic_praise_dynamic1_idx` (`dynamic_id` ASC),
  INDEX `fk_dynamic_praise_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_dynamic_praise_dynamic1`
    FOREIGN KEY (`dynamic_id`)
    REFERENCES `fudao`.`dynamic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dynamic_praise_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fudao`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '动态点赞';


-- -----------------------------------------------------
-- Table `fudao`.`chat_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`chat_type` (
  `id` INT NOT NULL COMMENT 'ID',
  `name` VARCHAR(45) NULL COMMENT '会话类型名称',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '会话类型，1：用户聊天，2：群组聊天。';


-- -----------------------------------------------------
-- Table `fudao`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`chat` (
  `id` VARCHAR(45) NOT NULL COMMENT '会话ID',
  `chat_type_id` INT NOT NULL COMMENT '会话类型ID',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `title` VARCHAR(45) NULL COMMENT '会话标题',
  `photo` VARCHAR(255) NULL COMMENT '会话头像',
  `last_message` VARCHAR(45) NULL COMMENT '最后一条消息内容',
  `update_time` DATETIME NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  INDEX `fk_chat_chat_type1_idx` (`chat_type_id` ASC),
  CONSTRAINT `fk_chat_chat_type1`
    FOREIGN KEY (`chat_type_id`)
    REFERENCES `fudao`.`chat_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '聊天';


-- -----------------------------------------------------
-- Table `fudao`.`message_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`message_type` (
  `id` INT NOT NULL COMMENT 'ID',
  `name` VARCHAR(45) NULL COMMENT '名称',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '消息类型';


-- -----------------------------------------------------
-- Table `fudao`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`message` (
  `id` VARCHAR(45) NOT NULL,
  `chat_id` VARCHAR(45) NOT NULL,
  `message_type_id` INT NOT NULL COMMENT '消息类型ID',
  `user_id` VARCHAR(45) NOT NULL,
  `content` VARCHAR(500) NULL,
  `create_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_message_chat1_idx` (`chat_id` ASC),
  INDEX `fk_message_message_type1_idx` (`message_type_id` ASC),
  INDEX `fk_message_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_message_chat1`
    FOREIGN KEY (`chat_id`)
    REFERENCES `fudao`.`chat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_message_type1`
    FOREIGN KEY (`message_type_id`)
    REFERENCES `fudao`.`message_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fudao`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fudao`.`user_friend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`user_friend` (
  `user_id` VARCHAR(45) NOT NULL COMMENT '用户ID',
  `friend_id` VARCHAR(45) NOT NULL COMMENT '好友ID',
  `create_time` DATETIME NULL COMMENT '加好友时间',
  `remark` VARCHAR(45) NULL COMMENT '好友备注',
  `dont_attention_him` TINYINT(1) NULL COMMENT '不关注他',
  `dont_let_him_attention` TINYINT(1) NULL COMMENT '不让他关注',
  INDEX `fk_friend_user1_idx` (`user_id` ASC),
  INDEX `fk_friend_user2_idx` (`friend_id` ASC),
  PRIMARY KEY (`user_id`, `friend_id`),
  CONSTRAINT `fk_friend_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fudao`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_friend_user2`
    FOREIGN KEY (`friend_id`)
    REFERENCES `fudao`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '好友';


-- -----------------------------------------------------
-- Table `fudao`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`group` (
  `id` VARCHAR(45) NOT NULL COMMENT 'ID',
  `name` VARCHAR(45) NULL COMMENT '群组名称',
  `photo` VARCHAR(255) NULL COMMENT '群组头像',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `user_id` VARCHAR(45) NOT NULL COMMENT '创建人ID',
  `master_id` VARCHAR(45) NOT NULL COMMENT '群主ID',
  PRIMARY KEY (`id`),
  INDEX `fk_group_user1_idx` (`user_id` ASC),
  INDEX `fk_group_user2_idx` (`master_id` ASC),
  CONSTRAINT `fk_group_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fudao`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_user2`
    FOREIGN KEY (`master_id`)
    REFERENCES `fudao`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '群组';


-- -----------------------------------------------------
-- Table `fudao`.`group_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`group_member` (
  `group_id` VARCHAR(45) NOT NULL COMMENT '群组ID',
  `user_id` VARCHAR(45) NOT NULL COMMENT '成员用户ID',
  `create_time` DATETIME NULL COMMENT '加入群的时间',
  INDEX `fk_group_member_group1_idx` (`group_id` ASC),
  INDEX `fk_group_member_user1_idx` (`user_id` ASC),
  PRIMARY KEY (`group_id`, `user_id`),
  CONSTRAINT `fk_group_member_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `fudao`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_member_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fudao`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '群组成员';


-- -----------------------------------------------------
-- Table `fudao`.`friend_apply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`friend_apply` (
  `user_id` VARCHAR(45) NOT NULL COMMENT '用户ID',
  `friend_id` VARCHAR(45) NOT NULL COMMENT '朋友ID',
  `introduce` VARCHAR(45) NULL COMMENT '自我介绍',
  `friend_remark` VARCHAR(45) NULL COMMENT '朋友备注',
  `create_time` DATETIME NULL COMMENT '申请时间',
  `status` INT NULL COMMENT '状态，',
  INDEX `fk_friend_apply_user1_idx` (`user_id` ASC),
  INDEX `fk_friend_apply_user2_idx` (`friend_id` ASC),
  PRIMARY KEY (`user_id`, `friend_id`),
  CONSTRAINT `fk_friend_apply_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fudao`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_friend_apply_user2`
    FOREIGN KEY (`friend_id`)
    REFERENCES `fudao`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '加好友申请';


-- -----------------------------------------------------
-- Table `fudao`.`emotion_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`emotion_type` (
  `id` INT NOT NULL COMMENT 'ID',
  `name` VARCHAR(45) NULL COMMENT '名称',
  `order_num` INT NULL COMMENT '排序号',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '情绪分类';


-- -----------------------------------------------------
-- Table `fudao`.`emotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`emotion` (
  `id` INT NOT NULL COMMENT 'ID',
  `name` VARCHAR(45) NULL COMMENT '名称',
  `emotion_type_id` INT NOT NULL COMMENT '情绪分类',
  `img` VARCHAR(255) NULL COMMENT '图标',
  `order_num` INT NULL COMMENT '排序号',
  PRIMARY KEY (`id`),
  INDEX `fk_emotion_emotion_type1_idx` (`emotion_type_id` ASC),
  CONSTRAINT `fk_emotion_emotion_type1`
    FOREIGN KEY (`emotion_type_id`)
    REFERENCES `fudao`.`emotion_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '情绪';


-- -----------------------------------------------------
-- Table `fudao`.`emotion_intervene_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`emotion_intervene_type` (
  `id` INT NOT NULL COMMENT 'ID',
  `name` VARCHAR(45) NULL COMMENT '名称',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '情绪干预类型';


-- -----------------------------------------------------
-- Table `fudao`.`emotion_intervene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`emotion_intervene` (
  `id` VARCHAR(45) NOT NULL COMMENT 'ID',
  `emotion_id` INT NOT NULL COMMENT '情绪ID',
  `title` VARCHAR(45) NULL COMMENT '标题',
  `content` TEXT NULL COMMENT '内容',
  `emotion_intervene_type_id` INT NOT NULL,
  `path` VARCHAR(255) NULL COMMENT '图片、音乐',
  `basis` TEXT NULL COMMENT '原理',
  PRIMARY KEY (`id`),
  INDEX `fk_emotion_intervene_emotion1_idx` (`emotion_id` ASC),
  INDEX `fk_emotion_intervene_emotion_intervene_type1_idx` (`emotion_intervene_type_id` ASC),
  CONSTRAINT `fk_emotion_intervene_emotion1`
    FOREIGN KEY (`emotion_id`)
    REFERENCES `fudao`.`emotion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emotion_intervene_emotion_intervene_type1`
    FOREIGN KEY (`emotion_intervene_type_id`)
    REFERENCES `fudao`.`emotion_intervene_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '情绪干预';


-- -----------------------------------------------------
-- Table `fudao`.`renqun_emotion_intervene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`renqun_emotion_intervene` (
  `renqun_id` INT NOT NULL,
  `emotion_intervene_id` VARCHAR(45) NOT NULL,
  INDEX `fk_renqun_emotion_intervene_renqun1_idx` (`renqun_id` ASC),
  INDEX `fk_renqun_emotion_intervene_emotion_intervene1_idx` (`emotion_intervene_id` ASC),
  CONSTRAINT `fk_renqun_emotion_intervene_renqun1`
    FOREIGN KEY (`renqun_id`)
    REFERENCES `fudao`.`renqun` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_renqun_emotion_intervene_emotion_intervene1`
    FOREIGN KEY (`emotion_intervene_id`)
    REFERENCES `fudao`.`emotion_intervene` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fudao`.`medical_examination_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`medical_examination_type` (
  `id` INT NOT NULL COMMENT 'ID',
  `name` VARCHAR(45) NULL COMMENT '名称',
  `order_num` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '体检项分类';


-- -----------------------------------------------------
-- Table `fudao`.`medical_examination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`medical_examination` (
  `id` VARCHAR(45) NOT NULL COMMENT 'ID',
  `name` VARCHAR(45) NULL COMMENT '名称',
  `medical_examination_type_id` INT NOT NULL COMMENT '分类ID',
  `order_num` INT NULL COMMENT '排序号',
  PRIMARY KEY (`id`),
  INDEX `fk_medical_examination_medical_examination_type1_idx` (`medical_examination_type_id` ASC),
  CONSTRAINT `fk_medical_examination_medical_examination_type1`
    FOREIGN KEY (`medical_examination_type_id`)
    REFERENCES `fudao`.`medical_examination_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '体检项';


-- -----------------------------------------------------
-- Table `fudao`.`user_medical_examination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fudao`.`user_medical_examination` (
  `user_id` VARCHAR(45) NOT NULL COMMENT '用户ID',
  `medical_examination_id` VARCHAR(45) NOT NULL COMMENT '体检项ID',
  `value` VARCHAR(45) NULL COMMENT '值',
  INDEX `fk_user_medical_examination_user1_idx` (`user_id` ASC),
  INDEX `fk_user_medical_examination_medical_examination1_idx` (`medical_examination_id` ASC),
  PRIMARY KEY (`user_id`, `medical_examination_id`),
  CONSTRAINT `fk_user_medical_examination_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fudao`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_medical_examination_medical_examination1`
    FOREIGN KEY (`medical_examination_id`)
    REFERENCES `fudao`.`medical_examination` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '用户体检';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
