export const good = [
  {
    name:'yuyue',
    title:'愉悦',
    img:require('../../assets/my-emotion/1yuyue.png')
  },
  {
    name:'xingfen',
    title:'兴奋',
    img:require('../../assets/my-emotion/2xingfen.png')
  },
  {
    name:'xingqu',
    title:'兴趣',
    img:require('../../assets/my-emotion/3xingqu.png')
  },
  {
    name:'manzu',
    title:'满足',
    img:require('../../assets/my-emotion/4manzu.png')
  }
]

export const calm = [
  {
    name:'pingjing',
    title:'平静',
    img:require('../../assets/my-emotion/5pingjing.png')
  }
]

export const bad = [
  {
    name:'shengqi',
    title:'生气',
    img:require('../../assets/my-emotion/6shengqi.png')
  },
  {
    name:'jusang',
    title:'沮丧',
    img:require('../../assets/my-emotion/7jusang.png')
  },
  {
    name:'jinzhang',
    title:'紧张',
    img:require('../../assets/my-emotion/8jinzhang.png')
  },
  {
    name:'kunhuo',
    title:'困惑',
    img:require('../../assets/my-emotion/9kunhuo.png')
  },
  {
    name:'wuliao',
    title:'无聊',
    img:require('../../assets/my-emotion/10wuliao.png')
  },
  {
    name:'zibei',
    title:'自卑',
    img:require('../../assets/my-emotion/11zibei.png')
  },
  {
    name:'caiyi',
    title:'猜疑',
    img:require('../../assets/my-emotion/12caiyi.png')
  },
  {
    name:'gudu',
    title:'孤独',
    img:require('../../assets/my-emotion/13gudu.png')
  },
  {
    name:'neijiu',
    title:'内疚',
    img:require('../../assets/my-emotion/14neijiu.png')
  },
  {
    name:'xianmu',
    title:'羡慕',
    img:require('../../assets/my-emotion/15xianmu.png')
  },
  {
    name:'xiukui',
    title:'羞愧',
    img:require('../../assets/my-emotion/16xiukui.png')
  },
  {
    name:'yanwu',
    title:'厌恶',
    img:require('../../assets/my-emotion/17yanwu.png')
  }
]
