const styles = {
  contain:{
    // backgroundColor:'#444',
    // flexDirection:'column',
  },
  color000:{
    color:'#000',
  },
  contain1:{
    backgroundColor:'#fff',
    flex:1,
  },
  content1:{
    height:180,
    marginBottom:30,
  },
  bgImg:{
    flex:1,
    alignItems:'center',
    justifyContent:'center',
    width:null,
    height:null,
  },
  person:{
    position:'absolute',
    top:160,
    right:100,
  },
  touxiang:{
    width:80,
    height:80,
    position:'absolute',
    top:120,
    right:10,
  },
  dynamic:{
    flexDirection:'row',
    marginRight:8,
    marginBottom:13,
    marginTop:6,
  },
  dynamicDetail:{
    flex:1,
  },
  dynamicTouxiang:{
    width:44,
    height:44,
    marginLeft:12,
    marginRight:12,
  },
  dynamicName:{
    color:'#0f9dc9',
    fontSize:17,
  },
  dynamicContent:{
    fontSize:15,
    marginTop:8,
  },
  imageTouch:{
    marginRight:7,
    marginTop:8,
    height: 120,
    width:78,
    height:78,
  },
  allImage:{
    flexDirection:'row',
    flexWrap:'wrap',
  },
  msgImage: {
    flex:1,
    alignItems:'center',
    justifyContent:'center',
    width:null,
    height:null,
  },
  dynamicMessage:{
    position:'absolute',
    right:0,
  },
  dynamicMessageImage:{
    width:16,
    height:16,
  },
  show:{
    flexDirection:'row',
    position:'absolute',
    right:24,

  },
  showone:{
    width:42,
  },
  showoneText:{
    textAlign:'center',
  },
  textInputContain:{
    paddingTop:10,
    paddingBottom:10,
    paddingLeft:10,
    paddingRight:10,
    position:'absolute',
    zIndex:99,
    bottom:0,
    flexDirection:'row',
    backgroundColor:'#fff',
  },
  textInput:{
    flex:1,
    height: 40,
    borderColor: 'gray',
    borderWidth: 1,
    borderRadius:10,
    paddingLeft:12,
  },
  allComments:{
    backgroundColor:'#eee',
    paddingLeft:10,
    marginRight:16,
    paddingBottom:8,
  },
  oneComment:{
    flexDirection:'row',
  },
  commentName:{
    color:'#0f9dc9',
    lineHeight:25,
    marginRight:6,
  },
  commentContent:{
    lineHeight:25,
  },
};

export default styles;
